### ISSUE TITLE
Scripts die al in de scene staan mogen geen Singleton zijn

### ISSUE THREAD

**Issue by NickyvanDokkum** [jscotty/HoneyWheresMyPhone#2]
Sommige van de scripts waar wij een Singleton van hadden gemaakt stonden al in de scene, dit geeft errors als de scene opnieuw wordt geladen.
Dus mot de code geconverteerd worden naar non singleton.

**Comment by bradakan** [comment]
De classes die geen singleton mogen extenden doen dat niet meer
